name: Update TAF y Excel

on:
  schedule:
    # Se ejecuta todos los días a las 09:30 UTC
    - cron: '00 4 * * *'
  workflow_dispatch: # permite ejecutarlo manualmente

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"

      - name: Crear carpeta data si no existe
        run: mkdir -p public/data

      - name: Descargar TAF
        run: |
          curl -s "https://tgftp.nws.noaa.gov/data/forecasts/taf/stations/MSLP.TXT" -o tmp_taf.txt
          day=$(date -u +'%d')
          taf_line=$(grep -m 1 "^TAF MSLP ${day}0325Z" tmp_taf.txt || true)
          if [ -n "$taf_line" ]; then
            echo "$taf_line" > public/data/taf-today.txt
          else
            echo "TAF no disponible aún para las 0325Z de hoy" > public/data/taf-today.txt
          fi

      - name: Descargar Excel operaciones.xlsx desde Drive
        run: |
          # Reemplaza URL_FINAL con tu enlace de descarga directa
          curl -L -o public/operaciones.xlsx "URL_FINAL"

      - name: Commit y push cambios
        run: |
          git add public/data/taf-today.txt public/operaciones.xlsx
          git commit -m "Update TAF y Excel $(date -u +'%Y-%m-%d')" || echo "No hay cambios para commitear"
          git push origin main
