name: Update TAF and XLSX

on:
  schedule:
    - cron: '0 5 * * *'   # Corre todos los días a las 05:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Setup folders
        run: mkdir -p public/data

      - name: Descargar TAF completo (solo si es de 03Z)
        run: |
          curl -s "https://tgftp.nws.noaa.gov/data/forecasts/taf/stations/MSLP.TXT" -o tmp_taf.txt

          # Extraer el bloque completo del último TAF
          taf_block=$(awk '/^TAF MSLP/{flag=1} flag{print} /^$/{if(flag){exit}}' tmp_taf.txt)

          # Validar si la hora de emisión está entre 0300Z y 0359Z
          if echo "$taf_block" | head -1 | grep -qE "03[0-5][0-9]Z"; then
            echo "$taf_block" > public/data/taf-today.txt
            echo "✅ TAF de 03Z capturado correctamente"
          else
            echo "NIL" > public/data/taf-today.txt
          fi

          echo "Contenido final de taf-today.txt:"
          cat public/data/taf-today.txt

      - name: Descargar operaciones.xlsx desde Google Drive
        run: |
          file_id="1VCS87YR2-O4tJLaJJMVAZtBTPYEQG9fQ"
          curl -L "https://drive.google.com/uc?export=download&id=${file_id}" -o public/operaciones.xlsx

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit y Push cambios
        run: |
          git add public/data/taf-today.txt public/operaciones.xlsx || true
          if git diff --cached --quiet; then
            echo "No hay cambios para commitear."
          else
            git commit -m "Update TAF and XLSX $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            git push origin main
          fi
