name: Update TAF Data

on:
  schedule:
    - cron: "30 9 * * *"  # todos los días a las 09:30 UTC
  workflow_dispatch:       # permite ejecutar manualmente

permissions:
  contents: write          # solo necesita permiso para modificar archivos del repo

jobs:
  update-taf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download TAF file
        run: |
          mkdir -p public/data
          curl -s "https://tgftp.nws.noaa.gov/data/forecasts/taf/stations/MSLP.TXT" -o public/data/taf.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --g
