name: Update TAF and XLSX

on:
  schedule:
    - cron: '30 4 * * *' # 0430 UTC cada día
  workflow_dispatch: # permite ejecutar manualmente

jobs:
  update-taf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Create data folder
        run: mkdir -p public/data

      - name: Download TAF
        run: |
          curl -s "https://tgftp.nws.noaa.gov/data/forecasts/taf/stations/MSLP.TXT" -o tmp_taf.txt
          day=$(date -u +'%d')
          taf_line=$(grep -m 1 "^TAF MSLP ${day}0325Z" tmp_taf.txt || true)
          if [ -n "$taf_line" ]; then
            echo "$taf_line" > public/data/taf-today.txt
          else
            echo "TAF no disponible aún para las 0325Z de hoy" > public/data/taf-today.txt
          fi

      - name: Download XLSX from Google Drive
        run: |
          curl -L -o public/operaciones.xlsx "https://drive.google.com/uc?export=download&id=1VCS87YR2-O4tJLaJJMVAZtBTPYEQG9fQ"

      - name: Commit changes
        run: |
          git add public/data/taf-today.txt public/operaciones.xlsx
          git commit -m "Update TAF $(date -u +'%Y-%m-%d')" || echo "No changes to commit"

      - name: Push changes
        run: git push origin main
