name: Update TAF and Operaciones

on:
  schedule:
    # Todos los días a las 03:30 UTC
    - cron: "30 3 * * *"
  workflow_dispatch: # Para ejecutarlo manualmente

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Descargar TAF publicado a las 03:25Z
      - name: Download TAF file
        run: |
          curl -s "https://tgftp.nws.noaa.gov/data/forecasts/taf/stations/MSLP.TXT" -o public/taf.txt

      # Descargar operaciones.xlsx desde Google Drive
      - name: Download operaciones.xlsx from Google Drive
        run: |
          FILE_ID="1VCS87YR2-O4tJLaJJMVAZtBTPYEQG9fQ"
          curl -L -o public/operaciones.xlsx "https://drive.google.com/uc?export=download&id=${FILE_ID}"

      # Commit y push de cambios
      - name: Commit and Push changes
        run: |
          git add public/taf.txt public/operaciones.xlsx
          git commit -m "Auto-update TAF y operaciones.xlsx ($(date -u +"%Y-%m-%d %H:%M:%S UTC"))" || echo "No changes to commit"
          git push
