name: Update TAF y Operaciones

# Triggers: diario a las 03:30 UTC y manual
on:
  schedule:
    - cron: '30 3 * * *'  # 03:30 UTC todos los días
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # No usar el GITHUB_TOKEN
          fetch-depth: 1

      - name: Configurar git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Crear carpeta de datos
        run: mkdir -p public/data

      - name: Descargar TAF
        run: |
          day=$(date -u +'%d')
          curl -s "https://tgftp.nws.noaa.gov/data/forecasts/taf/stations/MSLP.TXT" -o tmp_taf.txt
          taf_line=$(grep -m 1 "^TAF MSLP ${day}0325Z" tmp_taf.txt || true)
          if [ -n "$taf_line" ]; then
            echo "$taf_line" > public/data/taf-today.txt
          else
            echo "TAF no disponible aún para las 0325Z de hoy" > public/data/taf-today.txt
          fi
          echo "Contenido final de taf-today.txt:"
          cat public/data/taf-today.txt

      - name: Descargar XLSX desde Google Drive
        run: |
          FILE_ID="1VCS87YR2-O4tJLaJJMVAZtBTPYEQG9fQ"
          curl -L -o public/operaciones.xlsx "https://drive.google.com/uc?export=download&id=${FILE_ID}"

      - name: Verificar archivos descargados
        run: |
          if [ ! -s public/data/taf-today.txt ]; then
            echo "Error: taf-today.txt vacío"
            exit 1
          fi
          if [ ! -s public/operaciones.xlsx ]; then
            echo "Error: operaciones.xlsx vacío"
            exit 1
          fi

      - name: Commit y push solo si hay cambios
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add public/data/taf-today.txt public/operaciones.xlsx
          git diff --cached --quiet || git commit -m "Update TAF y operaciones.xlsx $(date -u +'%Y-%m-%d')"
          git push https://x-access-token:${GH_PAT}@github.com/sacomais/taf-site.git main
