name: Update TAF

on:
  schedule:
    # Ejecutar todos los días a las 03:30 UTC
    - cron: "30 3 * * *"
  workflow_dispatch: # Permite ejecución manual

permissions:
  contents: write   # Necesario para hacer git push

jobs:
  update-taf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create folders
        run: |
          mkdir -p public/data/history

      - name: Download full TAF file
        run: |
          curl -s "https://tgftp.nws.noaa.gov/data/forecasts/taf/stations/MSLP.TXT" -o tmp_taf.txt
          echo "Archivo descargado:"
          head -n 20 tmp_taf.txt

      - name: Extract today's 0325 UTC TAF
        run: |
          day=$(date -u +'%d')
          taf_line=$(grep -m 1 "^TAF MSLP ${day}0325Z" tmp_taf.txt || true)

          if [ -n "$taf_line" ]; then
            echo "$taf_line" > public/data/taf-today.txt
            echo "$taf_line" > "public/data/history/taf-$(date -u +'%Y-%m-%d').txt"
          else
            echo "TAF no disponible aún para las 0325Z de hoy" > public/data/taf-today.txt
          fi

          echo "Contenido final del taf-today.txt:"
          cat public/data/taf-today.txt

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/data/
          git commit -m "Update TAF $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
