name: Update TAF & XLSX

on:
  schedule:
    # Todos los días a las 0930 UTC
    - cron: '30 9 * * *'
  workflow_dispatch:

jobs:
  update-taf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up directories
        run: |
          mkdir -p public/data/history

      - name: Download TAF MSLP
        run: |
          curl -s "https://tgftp.nws.noaa.gov/data/forecasts/taf/stations/MSLP.TXT" -o tmp_taf.txt
          echo "Archivo descargado:"
          head -n 20 tmp_taf.txt

      - name: Extract today's TAF (0325Z)
        run: |
          day=$(date -u +'%d')
          taf_line=$(grep -m 1 "^TAF MSLP ${day}0325Z" tmp_taf.txt || true)
          
          if [ -n "$taf_line" ]; then
            echo "$taf_line" > public/data/taf-today.txt
            echo "$taf_line" > "public/data/history/taf-$(date -u +'%Y-%m-%d').txt"
          else
            echo "TAF no disponible aún para las 0325Z de hoy" > public/data/taf-today.txt
          fi

          echo "Contenido final del taf-today.txt:"
          cat public/data/taf-today.txt

      - name: Download operaciones.xlsx from Google Drive
        run: |
          curl -L -o public/operaciones.xlsx "https://docs.google.com/uc?export=download&id=${{ secrets.DRIVE_FILE_ID }}"

      - name: Commit & push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/data/taf-today.txt public/data/history/*.txt public/operaciones.xlsx
          git commit -m "Update TAF and operaciones.xlsx $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin main
